In [4]:
import pandas as pd
import csv

In [5]:
"""
book_id
title
author
publisher
year
isbn
image_url
description
call_number
stats
category
"""

'\nbook_id\ntitle\nauthor\npublisher\nyear\nisbn\nimage_url\ndescription\ncall_number\nstats\ncategory\n'

In [34]:
df = pd.read_csv("data2 copy.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")
raw = pd.read_csv("data.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")
raw

,자료명,저자,출판사,출판년도,청구기호,ISBN,썸네일,책소개,카테고리
0,(캠벨) 생명과학. 2: 6~8단원,Neil A. Campbell 외 지음; 전상학 외 역,바이오사이언스,2022,470 캠44ㅅ전-12 v.2 c.2,9788970000000,NaN,NaN,NaN
1,(캠벨) 생명과학. 2: 6~8단원,Neil A. Campbell 외 지음; 전상학 외 역,바이오사이언스,2022,470 캠44ㅅ전-12 v.2,9788970000000,NaN,NaN,NaN
2,The giver,Lois Lowry,Houghton Mifflin Harcourt,1993,843 L921g,9780540000000,NaN,NaN,NaN
3,Holes,Louis Sachar,Laurel leaf newbery,2023,843 L888h,9780440000000,NaN,NaN,NaN
4,신을 죽인 여자들,클라우디아 피녜이로 지음; 엄지영 옮김,푸른숲,2023,873 피194ㅅ엄,9791160000000,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
20691,10대의 뇌,프랜시스 젠슨;에이미 엘리스 넛 [공]지음; 김성훈 옮김,웅진지식하우스:웅진씽크빅,2018,511.1813 젠57ㅅ김,9788900000000,NaN,NaN,NaN
20692,델리에서 가장 아름다운 손,미카엘 베리스트란드 지음; 이승재 옮김,문학수첩,2018,859.7 베298ㄷ이,9788980000000,NaN,NaN,NaN
20693,시로 납치하다,류시화 지음,더숲,2018,811.6 류58ㅅㄹ,9791190000000,NaN,NaN,NaN
20694,내가 아무것도 아닐까 봐,박상아 지음,파우제:쎄듀,2018,818 박52ㄴ,9791200000000,NaN,NaN,NaN
20695,퇴근길엔 카프카를,의외의사실 글·그림,민음사,2018,818 의65ㅌ,9788940000000,NaN,NaN,NaN

In [35]:
raw['카테고리'] = raw['카테고리'].astype(object)

for index, row in raw.iterrows():
    df_row = df[df['자료명'] == row['자료명']]
    try:
        raw.at[index, '썸네일'] = df_row['카카오썸네일'].values[0]
        raw.at[index, '책소개'] = df_row['책소개'].values[0]
        raw.at[index, '카테고리'] = df_row['알라딘카테고리명'].values[0].split(">")
    except IndexError:
        raw.drop(index, inplace=True)

raw

C:\Users\yuni0\AppData\Local\Temp\ipykernel_22840\9542340.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://search1.kakaocdn.net/thumb/R120x174.q85/?fname=http%3A%2F%2Ft1.daumcdn.net%2Flbook%2Fimage%2F6039530%3Ftimestamp%3D20241001154924' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  raw.at[index, '썸네일'] = df_row['카카오썸네일'].values[0]
C:\Users\yuni0\AppData\Local\Temp\ipykernel_22840\9542340.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '『캠벨 생명과학』은 생물학 이론서이며 기초적이고 전반적인 내용을 확인할 수 있다.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  raw.at[index, '책소개'] = df_row['책소개'].values[0]

,자료명,저자,출판사,출판년도,청구기호,ISBN,썸네일,책소개,카테고리
0,(캠벨) 생명과학. 2: 6~8단원,Neil A. Campbell 외 지음; 전상학 외 역,바이오사이언스,2022,470 캠44ㅅ전-12 v.2 c.2,9788970000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,『캠벨 생명과학』은 생물학 이론서이며 기초적이고 전반적인 내용을 확인할 수 있다.,"[국내도서, 대학교재/전문서적, 자연과학계열, 생물학]"
1,(캠벨) 생명과학. 2: 6~8단원,Neil A. Campbell 외 지음; 전상학 외 역,바이오사이언스,2022,470 캠44ㅅ전-12 v.2,9788970000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,『캠벨 생명과학』은 생물학 이론서이며 기초적이고 전반적인 내용을 확인할 수 있다.,"[국내도서, 대학교재/전문서적, 자연과학계열, 생물학]"
2,The giver,Lois Lowry,Houghton Mifflin Harcourt,1993,843 L921g,9780540000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,"The Giver, the 1994 Newbery Medal winner, has ...","[외국도서, 어린이, 동화책, 고전/명작]"
4,신을 죽인 여자들,클라우디아 피녜이로 지음; 엄지영 옮김,푸른숲,2023,873 피194ㅅ엄,9791160000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,보르헤스 이후 가장 많은 언어로 번역된 아르헨티나의 대표 작가 클라우디아 피녜이로의...,"[국내도서, 소설/시/희곡, 추리/미스터리소설, 기타국가 추리/미스터리소설]"
5,알파폴드: AI 신약개발 혁신,남궁석 지음,Biospectator (바이오스펙테이터),2024,518.44 남16ㅇ,9791190000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,"바야흐로 인공지능의 시대다. 인공지능은 인류 문명을 다방면에서 바꿔 왔으며, 특히 ...","[국내도서, 과학, 생명과학, 생명과학]"
...,...,...,...,...,...,...,...,...,...
20691,10대의 뇌,프랜시스 젠슨;에이미 엘리스 넛 [공]지음; 김성훈 옮김,웅진지식하우스:웅진씽크빅,2018,511.1813 젠57ㅅ김,9788900000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,펜실베이니아대 의과대학 신경학과 교수 겸 학과장인 프랜시스 젠슨이 신생아에서 성인에...,"[국내도서, 과학, 뇌과학, 뇌과학 일반]"
20692,델리에서 가장 아름다운 손,미카엘 베리스트란드 지음; 이승재 옮김,문학수첩,2018,859.7 베298ㄷ이,9788980000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,하루 평균 2시간 33분. 업무 시간을 도둑질해 축구 팀 인터넷 사이트를 들락거렸다...,"[국내도서, 소설/시/희곡, 세계의 소설, 북유럽소설]"
20693,시로 납치하다,류시화 지음,더숲,2018,811.6 류58ㅅㄹ,9791190000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,"‘내가 만약 시인이라면 당신을 시로 납치할 거야. 시어와 운율로 당신을 사로잡고, ...","[국내도서, 소설/시/희곡, 시, 외국시]"
20694,내가 아무것도 아닐까 봐,박상아 지음,파우제:쎄듀,2018,818 박52ㄴ,9791200000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,숨 막히는 대중교통 출퇴근길과 누군가의 화받이로 전락한 직장생활 속에서도 ‘나는 중...,"[국내도서, 에세이, 한국에세이]"
20695,퇴근길엔 카프카를,의외의사실 글·그림,민음사,2018,818 의65ㅌ,9788940000000,https://search1.kakaocdn.net/thumb/R120x174.q8...,만화로 읽는 열세 편의 인생 고전 에세이 『퇴근길엔 카프카를』. 셰익스피어부터 카프...,"[국내도서, 에세이, 사진/그림 에세이]"

In [38]:
raw.reset_index(drop=True, inplace=True)

raw.to_csv("data3.csv", index=True, encoding="utf-8",quoting=csv.QUOTE_ALL,escapechar="\\")

In [125]:
df = pd.read_csv("data3.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")

In [127]:
del df['Unnamed: 0']

In [128]:
df['isbn'] = df['isbn'].str.replace(" ", "")


df['year'] = df['year'].astype(int)

df['category'] = df['category'].astype(object)

In [137]:
df.to_csv("data3.csv", index=False, encoding="utf-8",quoting=csv.QUOTE_ALL,escapechar="\\")

In [138]:
df = pd.read_csv("data3.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")

df['isbn'] = df['isbn'].astype(str)
df['year'] = df['year'].astype(int)
df['image_url'] = df['image_url'].astype(str)

def to_pg_array(s):
    s = s.replace("{", "[")
    s = s.replace("}", "]")
    s = s.split(",")
    s = [item.replace("'", '"') for item in s]
    return "{" + ",".join(f"{item}" for item in s) + "}"

df['category'] = df['category'].apply(lambda x: to_pg_array(x))

df['category']

0                    {["대학교재/전문서적","자연과학계열","생물학"]}
1                    {["대학교재/전문서적","자연과학계열","생물학"]}
2                           {["어린이","동화책","고전/명작"]}
3        {["소설/시/희곡","추리/미스터리소설","기타국가 추리/미스터리소설"]}
4                            {["과학","생명과학","생명과학"]}
                            ...
10932                       {["과학","뇌과학","뇌과학 일반"]}
10933                {["소설/시/희곡","세계의 소설","북유럽소설"]}
10934                       {["소설/시/희곡","시","외국시"]}
10935                             {["에세이","한국에세이"]}
10936                         {["에세이","사진/그림 에세이"]}
Name: category, Length: 10937, dtype: object

In [139]:
df['category'] = df['category'].apply(lambda x: x.replace("[", "").replace("]", ""))
df['category']

0                    {"대학교재/전문서적","자연과학계열","생물학"}
1                    {"대학교재/전문서적","자연과학계열","생물학"}
2                           {"어린이","동화책","고전/명작"}
3        {"소설/시/희곡","추리/미스터리소설","기타국가 추리/미스터리소설"}
4                            {"과학","생명과학","생명과학"}
                           ...
10932                       {"과학","뇌과학","뇌과학 일반"}
10933                {"소설/시/희곡","세계의 소설","북유럽소설"}
10934                       {"소설/시/희곡","시","외국시"}
10935                             {"에세이","한국에세이"}
10936                         {"에세이","사진/그림 에세이"}
Name: category, Length: 10937, dtype: object

In [ ]:
df['category'] = df['category'].apply(lambda x: x.replace('""', '"')[1:-1])

In [145]:
df = pd.read_csv("data3.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")

df['category'] = df['category'].astype(str)
df['category']

0                    {"대학교재/전문서적","자연과학계열","생물학"}
1                    {"대학교재/전문서적","자연과학계열","생물학"}
2                           {"어린이","동화책","고전/명작"}
3        {"소설/시/희곡","추리/미스터리소설","기타국가 추리/미스터리소설"}
4                            {"과학","생명과학","생명과학"}
                           ...
10932                       {"과학","뇌과학","뇌과학 일반"}
10933                {"소설/시/희곡","세계의 소설","북유럽소설"}
10934                       {"소설/시/희곡","시","외국시"}
10935                             {"에세이","한국에세이"}
10936                         {"에세이","사진/그림 에세이"}
Name: category, Length: 10937, dtype: object

In [148]:
df.to_csv("data3.csv", index=False, encoding="utf-8",escapechar="\\")

In [147]:
df = pd.read_csv("data3.csv", quoting=csv.QUOTE_ALL, escapechar="\\", encoding="utf-8")
df['category']

0                    {"대학교재/전문서적","자연과학계열","생물학"}
1                    {"대학교재/전문서적","자연과학계열","생물학"}
2                           {"어린이","동화책","고전/명작"}
3        {"소설/시/희곡","추리/미스터리소설","기타국가 추리/미스터리소설"}
4                            {"과학","생명과학","생명과학"}
                           ...
10932                       {"과학","뇌과학","뇌과학 일반"}
10933                {"소설/시/희곡","세계의 소설","북유럽소설"}
10934                       {"소설/시/희곡","시","외국시"}
10935                             {"에세이","한국에세이"}
10936                         {"에세이","사진/그림 에세이"}
Name: category, Length: 10937, dtype: object